services:
  - type: web
    name: schedule-to-ical
    env: python
    plan: starter # or free if testing
    buildCommand: |
      apt-get update && apt-get install -y chromium-browser chromium-chromedriver
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: CHROME_BIN
        value: /usr/bin/chromium-browser
      - key: CHROMEDRIVER_PATH
        value: /usr/bin/chromedriver
